# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Factor.create([{ detalle: 'Mision proyecto institucional' },
               { detalle: 'Estudiantes' },
               { detalle: 'Profesores' },
               { detalle: 'Procesos académicos' },
               { detalle: 'Visibilidad nacional e internacional' },
               { detalle: 'Espacion de investigación, innovación, y creación artística y cultural' },
               { detalle: 'Pertinecia e impacto social' },
               { detalle: 'Autoevaluación y Autorregulacón' },
               { detalle: 'Bienestar institucional' },
               { detalle: 'Organización, Gestión y administración' },
               { detalle: 'Recursos de apoyo académico e infraestructura física' },
               { detalle: 'Recursos financieros' }])

Indicator.create([{ detalle: 'Barreras para el aprendizaje y la participación', factor_id: 1 },
                  { detalle: 'Identificación y caracterización de estudiantes desde la educación inclusiva', factor_id: 1 },
                  { detalle: 'Participación de estudiantes', factor_id: 2 },
                  { detalle: 'Admisión, permanencia y sistemas de estímulos y créditos para estudiantes', factor_id: 2 },
                  { detalle: 'Participación de estudiantes', factor_id: 2 },
                  { detalle: 'Admisión, permanencia y sistemas de estímulos y créditos para estudiantes', factor_id: 3 },
                  { detalle: 'Participación de docentes', factor_id: 3 },
                  { detalle: 'Docentes inclusivos', factor_id: 3 },
                  { detalle: 'Interdisciplinariedad y flexibilidad curricular', factor_id: 4 },
                  { detalle: 'Evaluación flexible', factor_id: 4 },
                  { detalle: 'Inserción de la institución en contextos académicos nacionales e internacionales', factor_id: 5 },
                  { detalle: 'Relaciones externas de profesores y estudiantes', factor_id: 5 },
                  { detalle: 'Investigación, innovación y creación artística y cultural en educación inclusiva', factor_id: 6 },
                  { detalle: 'Articulación de la educación inclusiva con los procesos de investigación, innovación y creación artística y cultural', factor_id: 6 },
                  { detalle: 'Extensión, proyección social y contexto regional', factor_id: 7 },
                  { detalle: 'Seguimiento y apoyo a vinculación laboral', factor_id: 7 },
                  { detalle: 'Procesos de autoevaluación y autorregulación con enfoque de educación inclusiva', factor_id: 8 },
                  { detalle: 'Estrategias de mejoramiento', factor_id: 8 },
                  { detalle: 'Sistema de información inclusivo', factor_id: 8 },
                  { detalle: 'Procesos administrativos y de gestión flexibles', factor_id: 9 },
                  { detalle: 'Estructura organizacional', factor_id: 9 },
                  { detalle: 'Recursos, equipos y espacios de práctica', factor_id: 10 },
                  { detalle: 'Instalaciones e infraestructura', factor_id: 10 },
                  { detalle: 'Programas de bienestar universitario', factor_id: 11 },
                  { detalle: 'Permanencia estudiantil', factor_id: 11 },
                  { detalle: 'Programas de educación inclusiva sostenibles', factor_id: 12 },
                  { detalle: 'Apoyo financiero a estudiantes', factor_id: 12 }])

Question.create([{ detalle: 'Contemplan la misión y el proyecto de la institución las seis características de la educación inclusiva pensando en la eliminación de estas barreras', indicator_id: 1},
                 { detalle: 'Existe en la institución una instancia responsable de examinar cuáles son estas barreras', indicator_id: 1},
                 { detalle: 'Si estas barreras han sido identificadas, se han implementado estrategias concretas para su eliminación', indicator_id: 1},
                 { detalle: 'Cuenta la institución con un acto administrativo o una resolución que priorice las particularidades sociales, económicas, políticas, culturales, lingüísticas, físicas y geográficas de sus estudiantes, con el fin de facilitar el acceso y la permanencia', indicator_id: 1},
                 { detalle: 'Cuenta la institución con estudios sobre las condiciones de su población estudiantil (sociales, económicas, políticas, culturales, lingüísticas, físicas y geográficas) y usa esta información para desarrollar estrategias de educación inclusiva', indicator_id: 2},
                 { detalle: 'La identificación y caracterización estudiantil es una prioridad para determinar a los estudiantes más proclives a ser excluidos del sistema', indicator_id: 2},
                 { detalle: 'Recoge y sistematiza la institución, en los procesos de matrícula, información sobre las condiciones particulares de sus estudiantes', indicator_id: 2},
                 { detalle: 'La participación de los estudiantes en la institución está identificada de manera explícita en la política institucional', indicator_id: 3},
                 { detalle: 'Existen documentos de análisis institucionales sobre los resultados de los estudios de identificación y caracterización estudiantil', indicator_id: 2},
                 { detalle: 'Existen mecanismos de participación para que los estudiantes elijan los contenidos y las estrategias de enseñanza y aprendizaje en pro de la educación inclusiva', indicator_id: 3},
                 { detalle: 'Desempeñan los estudiantes un rol activo en el desarrollo de la política institucional', indicator_id: 3},
                 { detalle: 'Existen apoyos que garanticen la aplicación equitativa y transparente de los criterios para la admisión y permanencia de los estudiantes, especialmente aquellos que tienen una condición de vulnerabilidad', indicator_id: 4},
                 { detalle: 'Garantiza la institución la participación de todos los estudiantes, teniendo en cuenta sus particularidades sociales, económicas, políticas, culturales, lingüísticas, físicas y geográficas', indicator_id: 3},
                 { detalle: 'Existen análisis sobre la deserción de estudiantes, sus causas y posibles estrategias para garantizar su permanencia en condiciones de calidad', indicator_id: 4},
                 { detalle: 'Existen  estrategias  que garanticen  la inclusión de los estudiantes  a la institución  sin importar   su condición', indicator_id: 4},
                 { detalle: 'Existe un procedimiento claro de control para garantizar que los estudiantes beneficiados con los apoyos institucionales hagan buen uso de estos en los tiempos previstos para su graduación', indicator_id: 4},
                 { detalle: 'Se cuenta con una divulgación de los sistemas de crédito, subsidios, becas y estímulos', indicator_id: 4},
                 { detalle: 'Existen mecanismos de participación para que los docentes elijan los contenidos y las estrategias de enseñanza y aprendizaje en pro de la educación inclusiva', indicator_id: 5},
                 { detalle: 'La participación de los docentes en la institución está identificada de manera explícita en la política institucional', indicator_id: 5},
                 { detalle: 'Existen lineamientos institucionales que definan las cualidades del “docente inclusivo”', indicator_id: 6},
                 { detalle: 'Garantiza la institución la participación de todos los docentes, teniendo en cuenta sus particularidades sociales, económicas, políticas, culturales, lingüísticas, físicas y geográficas', indicator_id: 5},
                 { detalle: 'Cuentan los docentes con procesos de formación permanente sobre educación inclusiva  y atención a la diversidad, independientemente de su tipo de vinculación y área del conocimiento', indicator_id: 6},
                 { detalle: 'Se comparten estrategias pedagógicas y metodológicas de educación inclusiva entre  los docentes para ser aplicadas en los procesos académicos, y promueve la institución la retroalimentación de estas estrategias', indicator_id: 6},
                 { detalle: 'Contemplan los currículos metodologías flexibles en atención a la diversidad para la enseñanza y aprendizaje', indicator_id: 7},
                 { detalle: 'Los docentes evidencian y valoran en sus estrategias de enseñanza la diversidad de sus estudiantes', indicator_id: 6},
                 { detalle: 'Los currículos se flexibilizan de acuerdo con las particularidades del entorno y los contextos regionales, desde una perspectiva interdisciplinar', indicator_id: 7},
                 { detalle: 'Implementan los planes de estudio didácticas innovadoras que tienen en cuenta las particularidades de los estudiantes en los procesos de aprendizaje y desarrollo de sus capacidades', indicator_id: 7},
                 { detalle: 'Existe un servicio de apoyo pedagógico reconocido –tutorías, cursos de nivelación, entre otros– para todos los estudiantes que lo requieran', indicator_id: 7},
                 { detalle: 'La utilización de las TIC en el desarrollo de los currículos permite facilitar el aprendizaje y la participación de todos los estudiantes', indicator_id: 7},
                 { detalle: 'Se evidencia la importancia de la evaluación flexible en la política institucional', indicator_id: 8},
                 { detalle: 'Los procesos de evaluación implementan estrategias y/o herramientas diferenciales  de apoyo  que permiten lograr la equidad entre los estudiantes', indicator_id: 8},
                 { detalle: 'Existen lineamientos institucionales que orienten al docente sobre el diseño y la implementación de una evaluación flexible', indicator_id: 8},
                 { detalle: 'Las herramientas de evaluación son socializadas y concertadas con estudiantes y docentes antes de ser implementadas, con el fin de tener en cuenta la diversidad', indicator_id: 8},
                 { detalle: 'Existe análisis sistemático realizado por la institución frente a temas de inclusión con respecto a otras instituciones nacionales e internacionales para realizar acciones y planes de mej', indicator_id: 9},
                 { detalle: 'Existe y aplica políticas institucionales  en  materia  de  referentes  académicos  externos, nacionales e internacionales, de reconocida calidad para la revisión y actualización  de los planes  de estudio', indicator_id: 9},
                 { detalle: 'con miembros de comunidades nacionales e internacionales de reconocido liderazgo en temas específicos de inclusión', indicator_id: 9},
                 { detalle: 'Existen proyectos de investigación, innovación, creación artística y cultural y/o proyección –de acuerdo con la naturaleza de la institución– desarrollados como producto de la cooperación académica y profesional, realizada por directivos, profesores y estudiantes de la institución', indicator_id: 9},
                 { detalle: 'Existe alianzas interinstitucionales para compartir recursos, impulsar procesos misionales y buenas prácticas de inclusión', indicator_id: 9},
                 { detalle: 'Se cuenta con evidencias del impacto social que ha generado la inserción de la institución en los contextos académicos nacionales e internacionales en cuanto a temas de inclusión', indicator_id: 9},
                 { detalle: 'Se cuenta con una RED académica, científica, técnica o tecnológica a nivel nacional e internacional, en la que se revisen temas de inclusión en la educación superior por parte de profesores, estudiantes y directivos de la institución', indicator_id: 10},
                 { detalle: 'Existen convenios con enfoque de inclusión activos de intercambio con instituciones de educación superior nacionales y extranjeras de alta calidad y reconocimiento', indicator_id: 10},
                 { detalle: 'Existen centros o grupos de investigación en la IES que desarrollen temas relacionados con educación inclusiva y promueven estrategias basadas en los principios in', indicator_id: 11},
                 { detalle: 'Existen productos concretos, como publicaciones, en coautoría en revistas indexadas, con visibilidad e impacto, cofinanciación de proyectos, registros y patentes, entre otros productos de las REDES', indicator_id: 10},
                 { detalle: 'La educación inclusiva está considerada como un eje transversal en los procesos de investigación de la institución', indicator_id: 11},
                 { detalle: 'Se articulan estos centros, grupos y/o programas con los actores y contextos regionales', indicator_id: 11},
                 { detalle: 'Los centros, grupos y/o programas promueven la participación de los estudiantes en los procesos de investigación', indicator_id: 11},
                 { detalle: 'La investigación  en educación inclusiva en la institución  es entendida desde lo interdisciplinar  y  el diálogo de saberes', indicator_id: 12},
                 { detalle: 'La institución cuenta con el apoyo de expertos en educación inclusiva que le permiten promover el tema de manera adecuada', indicator_id: 12},
                 { detalle: 'Los procesos académicos fomentan la creación de semilleros de investigación y líneas de profundización desde un enfoque de educación inclusiva', indicator_id: 12},
                 { detalle: 'Participa la IES en convenios interinstitucionales para el desarrollo de investigaciones en el marco de la educación inclusiva', indicator_id: 12},
                 { detalle: 'Los programas de extensión permiten identificar las problemáticas regionales y articular las actividades académicas con el contexto desde las dimensiones de la educación inclusiva', indicator_id: 13},
                 { detalle: 'Existe en la IES un trabajo de intercambio de experiencias con las comunidades para identificar sus necesidades y potencialidades', indicator_id: 13},
                 { detalle: 'Existen actividades y proyectos sociales tendientes a procurar el bienestar general de la comunidad, teniendo en cuenta sus necesidades regionales y poblacionales', indicator_id: 13},
                 { detalle: 'La institución promueve la participación de estudiantes y docentes en dichas actividades y proyectos', indicator_id: 13},
                 { detalle: 'La IES cuenta con un sistema de seguimiento a los egresados, a través del cual es posible analizar las dificultades que se encuentran al vincularse al mundo laboral', indicator_id: 14},
                 { detalle: 'Este sistema contempla variables de análisis diferenciales por grupos poblaciones', indicator_id: 14},
                 { detalle: 'La IES contempla, dentro de sus planes de trabajo, el apoyo a egresados que encuentran dificultades para el ingreso al mundo laboral, en especial a los estudiantes indígenas, afrocolombianos, raizales y palenqueros, víctimas del conflicto, desmovilizados y/o en situación  de discapacidad', indicator_id: 14},
                 { detalle: 'La institución desarrolla estrategias con el sector productivo para fomentar la vinculación laboral de sus estudiantes', indicator_id: 14},
                 { detalle: 'Los procesos de autoevaluación y  autorregulación  han  sido  construidos  para  tener  en  cuenta los avances y dificultades de la articulación del enfoque de educación inclusiva en la institución', indicator_id: 15},
                 { detalle: 'La institución cuenta con un sistema de autoevaluación y autorregulación institucional donde participa toda la comunidad académica, y en especial los estudiantes', indicator_id: 15},
                 { detalle: 'Se involucran los diferentes estamentos de la institución en la construcción de estrategias de autoevaluación y autorregulación', indicator_id: 15},
                 { detalle: 'El sistema de autoevaluación y autorregulación es accesible a toda la comunidad académica, y en especial a las personas en situación de discapacidad visual y/o auditiva', indicator_id: 15},
                 { detalle: 'Los planes de mejoramiento institucionales surgen de los resultados de las autoevaluaciones y evaluaciones', indicator_id: 16},
                 { detalle: 'Los planes de mejoramiento se formulan con el objetivo de articular las prácticas institucionales al enfoque de educación inclusiva', indicator_id: 16},
                 { detalle: 'Existen espacios formales e informales en los que se compartan con toda la comunidad académica los resultados de las autoevaluaciones y evaluaciones, y las estrategias de mejoramiento', indicator_id: 16},
                 { detalle: 'La información obtenida del sistema se utiliza como fundamento para mejorar los procesos de educación inclusiva en la institución', indicator_id: 17},
                 { detalle: 'La información institucional está disponible para todos', indicator_id: 17},
                 { detalle: 'Existen mecanismos de validación de la información y se dice quiénes participan en estos', indicator_id: 17},
                 { detalle: 'Cumple este sistema con las condiciones de accesibilidad, en especial para los miembros de la comunidad en situación de discapacidad', indicator_id: 17},
                 { detalle: 'El contenido de los programas  de bienestar  universitario  tiene como  base las características  de  la educación inc', indicator_id: 18},
                 { detalle: 'Se implementan estrategias accesibles para que todos  los estudiantes  conozcan  e identifiquen los programas de bienestar universitario, como parte central de  la  política  institucional  (y  no como algo complementario)', indicator_id: 18},
                 { detalle: 'Existen acciones definidas enfocadas a mejorar la calidad de vida y la formación integral de los estudiantes, teniendo como referente sus particularidades', indicator_id: 18},
                 { detalle: 'La IES cuenta con mecanismos de seguimiento académico de los estudiantes con el fin de identificar los riesgos asociados a la deserción', indicator_id: 19},
                 { detalle: 'La IES diseña estrategias de nivelación académica de los estudiantes teniendo en cuenta sus particularidades sociales, económicas, políticas, culturales, lingüísticas, físicas y geográficas', indicator_id: 19},
                 { detalle: 'La IES adelanta estrategias de orientación socio-ocupacional con los estudiantes', indicator_id: 19},
                 { detalle: 'Las procesos administrativos reflejan  los objetivos  de la política institucional evocada en los indicadores del factor “misión y proyecto institucional”; es decir, están articulados para eliminar las barreras propias del sistema y atender las particularidades de los estudiantes', indicator_id: 20},
                 { detalle: 'Existen mecanismos que garanticen la participación de la comunidad académica en la construcción y evaluación de estos procesos', indicator_id: 20},
                 { detalle: 'El personal administrativo encargado de llevar estos procesos tiene conocimiento de lo que representa la educación inclusiva para la institución y está cualificado para promoverla en su trabajo', indicator_id: 20},
                 { detalle: 'El lenguaje institucional que se utiliza en estos procesos es coherente con los conceptos que caracterizan la educación inclusiva', indicator_id: 20},
                 { detalle: 'La institución realiza procesos de gestión, como convenios de cooperación, intercambios estudiantiles, alianzas estratégicas, con organizaciones e instituciones de educación superior (nacionales o internacionales) para promover acciones de educación inclusiva', indicator_id: 20},
                 { detalle: 'La estructura organizacional permite la participación de toda la comunidad académica, en especial la de los estudiantes', indicator_id: 21},
                 { detalle: 'Se tienen en cuenta las buenas prácticas de instituciones pares sobre educación inclusiva para mejorar la estructura organizacional de la institución', indicator_id: 21},
                 { detalle: 'La institución adapta su estructura organizacional teniendo en cuenta la diversidad de su comunidad académica', indicator_id: 21},
                 { detalle: 'La educación inclusiva se identifica como un eje transversal en la estructura organizacional', indicator_id: 21},
                 { detalle: 'Se tienen en cuenta las opiniones y necesidades de la comunidad académica para la adecuación de instalaciones, recursos académicos y físicos necesarios', indicator_id: 22},
                 { detalle: 'Existe un estudio que permita identificar si las adecuaciones físicas de la institución favorecen el desarrollo de procesos académicos inclusivos', indicator_id: 22},
                 { detalle: 'Se desarrollan los acompañamientos requeridos para que todo estudiante pueda hacer uso de los recursos, equipos y espacios de práctica', indicator_id: 22},
                 { detalle: 'La institución desarrolla programas de uso y apropiación de los equipos y medios educativos con toda la comunidad académica (y no exclusivamente con aquellas personas que requieren estos equipos y medios)', indicator_id: 22},
                 { detalle: 'La institución conoce y aplica la normatividad de accesibilidad y diseño universal para la participación de toda la comunidad académica', indicator_id: 23},
                 { detalle: 'Dentro de los planes institucionales existe una línea específica para el mejoramiento y accesibilidad de la infraestructura', indicator_id: 23},
                 { detalle: 'Se cuenta con un plan de mejoramiento orientado a eliminar específicamente las barreras de acceso de la infraestructura institucional', indicator_id: 23},
                 { detalle: 'Se tiene en cuenta la necesidad de la comunidad académica para el diseño de la política encaminada a reducir las barreras de acceso', indicator_id: 23},
                 { detalle: 'Las estrategias de educación inclusiva y los recursos relacionados son una prioridad en la agenda institucional', indicator_id: 24},
                 { detalle: 'En sus ejercicios de planeación, la institución contempla la destinación de recursos para favorecer la educación inclusiva', indicator_id: 24},
                 { detalle: 'Concurren actores externos para el financiamiento de las estrategias institucionales de educación inclusiva', indicator_id: 24},
                 { detalle: 'Existe un mecanismo que permita  garantizar  la implementación  y la sostenibilidad financiera de los programas, estrategias y proyectos para promover la  educación  inclusiva  en  la institución', indicator_id: 24},
                 { detalle: 'La institución desarrolla una caracterización para identificar las dificultades económicas de los estudiantes', indicator_id: 25},
                 { detalle: 'Existen políticas institucionales que faciliten el acceso y la permanencia de los estudiantes en términos financieros para apoyar gastos de sostenimiento, fotocopias, libros, herramientas de trabajo, entre otros', indicator_id: 25},
                 { detalle: 'La institución dispone de un fondo específico para este tipo de financiación', indicator_id: 25},
                 { detalle: 'La institución cuenta con profesionales de apoyo, como intérpretes, tutores,  lectores  y guías que favorecen el acceso y la permanencia de los estudiantes que lo requieran', indicator_id: 25}])

